### ISSUE TITLE
Salzhügel

### ISSUE THREAD

**Issue by VaeterchenFrost** [rflorian/fwstyle#2]
Markierung Salzhügel nach 
http://www.fwwiki.de/index.php/Karte:Orewu#MapNPCFilter_Lebender%20Salzh%C3%BCgel

**Comment by VaeterchenFrost** [comment]
`/* Living Salthill */
#mapx110y113 { background-image: linear-gradient(rgba(102, 204, 0, 0.7), rgba(102, 204, 0, 0.7)), url(http://welt1.freewar.de/freewar/images/map/salzs1.jpg) !important; background-size: 40% 40%, 100% 100%; background-position: bottom right; background-repeat: no-repeat, no-repeat;}
#mapx107y114 { background-image: linear-gradient(rgba(102, 204, 0, 0.7), rgba(102, 204, 0, 0.7)), url(http://welt1.freewar.de/freewar/images/map/salzs18.jpg) !important; background-size: 40% 40%, 100% 100%; background-position: bottom right; background-repeat: no-repeat, no-repeat;}
#mapx111y114 { background-image: linear-gradient(rgba(102, 204, 0, 0.7), rgba(102, 204, 0, 0.7)), url(http://welt1.freewar.de/freewar/images/map/salzs28.jpg) !important; background-size: 40% 40%, 100% 100%; background-position: bottom right; background-repeat: no-repeat, no-repeat;}
#mapx108y115 { background-image: linear-gradient(rgba(102, 204, 0, 0.7), rgba(102, 204, 0, 0.7)), url(http://welt1.freewar.de/freewar/images/map/salzs8.jpg) !important; background-size: 40% 40%, 100% 100%; background-position: bottom right; background-repeat: no-repeat, no-repeat;}
#mapx109y115 { background-image: linear-gradient(rgba(102, 204, 0, 0.7), rgba(102, 204, 0, 0.7)), url(http://welt1.freewar.de/freewar/images/map/salzs15.jpg) !important; background-size: 40% 40%, 100% 100%; background-position: bottom right; background-repeat: no-repeat, no-repeat;}
#mapx111y115 { background-image: linear-gradient(rgba(102, 204, 0, 0.7), rgba(102, 204, 0, 0.7)), url(http://welt1.freewar.de/freewar/images/map/salzs49.jpg) !important; background-size: 40% 40%, 100% 100%; background-position: bottom right; background-repeat: no-repeat, no-repeat;}
#mapx113y115 { background-image: linear-gradient(rgba(102, 204, 0, 0.7), rgba(102, 204, 0, 0.7)), url(http://welt1.freewar.de/freewar/images/map/salzs52.jpg) !important; background-size: 40% 40%, 100% 100%; background-position: bottom right; background-repeat: no-repeat, no-repeat;}
#mapx108y116 { background-image: linear-gradient(rgba(102, 204, 0, 0.7), rgba(102, 204, 0, 0.7)), url(http://welt1.freewar.de/freewar/images/map/salzs49.jpg) !important; background-size: 40% 40%, 100% 100%; background-position: bottom right; background-repeat: no-repeat, no-repeat;}
#mapx112y116 { background-image: linear-gradient(rgba(102, 204, 0, 0.7), rgba(102, 204, 0, 0.7)), url(http://welt1.freewar.de/freewar/images/map/salzs49.jpg) !important; background-size: 40% 40%, 100% 100%; background-position: bottom right; background-repeat: no-repeat, no-repeat;}
#mapx110y117 { background-image: linear-gradient(rgba(102, 204, 0, 0.7), rgba(102, 204, 0, 0.7)), url(http://welt1.freewar.de/freewar/images/map/salzs21.jpg) !important; background-size: 40% 40%, 100% 100%; background-position: bottom right; background-repeat: no-repeat, no-repeat;}
#mapx112y117 { background-image: linear-gradient(rgba(102, 204, 0, 0.7), rgba(102, 204, 0, 0.7)), url(http://welt1.freewar.de/freewar/images/map/salzs8.jpg) !important; background-size: 40% 40%, 100% 100%; background-position: bottom right; background-repeat: no-repeat, no-repeat;}
#mapx110y118 { background-image: linear-gradient(rgba(102, 204, 0, 0.7), rgba(102, 204, 0, 0.7)), url(http://welt1.freewar.de/freewar/images/map/salzs26.jpg) !important; background-size: 40% 40%, 100% 100%; background-position: bottom right; background-repeat: no-repeat, no-repeat;}
#mapx111y118 { background-image: linear-gradient(rgba(102, 204, 0, 0.7), rgba(102, 204, 0, 0.7)), url(http://welt1.freewar.de/freewar/images/map/salzs24.jpg) !important; background-size: 40% 40%, 100% 100%; background-position: bottom right; background-repeat: no-repeat, no-repeat;}
`

**Comment by rflorian** [comment]
inserted
